# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Weather-Logger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for Weather-Logger
  pod "PromiseKit", "~> 6.8"
  pod "PromiseKit/CoreLocation", "~> 6.0"
  pod 'RealmSwift'
  pod 'RxSwift', '6.0.0'
  pod 'RxCocoa', '6.0.0'
end
